from rnn_util import *

B2 = {
    "dataset_splitter" : split_dataset_random_05,
    "lookup_phi" : response_index_phi,
    "data_reader" : pol_reader,
    "balanced_setting" : True,
    "max_len" : 60,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 10,
    "dropout" : 0.1,
    "l2_lambda" : 1e-4,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : False,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 5,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

B3 = {
    "dataset_splitter" : split_dataset_random_05,
    "lookup_phi" : response_index_phi,
    "data_reader" : pol_reader,
    "balanced_setting" : True,
    "author_phi_creator" : author_comment_counts_phi_creator,
    "author_feature_shape_placeholder" : (2,),
    "max_len" : 60,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 10,
    "dropout" : 0.1,
    "l2_lambda" : 1e-4,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : False,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 5,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

B4 = {
    "dataset_splitter" : split_dataset_random_05,
    "lookup_phi" : response_index_phi,
    "data_reader" : pol_reader,
    "balanced_setting" : True,
    "author_phi_creator" : author_index_phi_creator,
    "author_feature_shape_placeholder" : (None, 15),
    "max_len" : 100,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 160,
    "dropout" : 0.3,
    "l2_lambda" : .001,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : True,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 5,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

C2 = {
    "dataset_splitter" : split_dataset_random_plus_politics,
    "lookup_phi" : response_index_phi,
    "data_reader" : full_reader,
    "balanced_setting" : True,
    "max_len" : 60,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 10,
    "dropout" : 0.1,
    "l2_lambda" : 1e-4,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : False,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 5,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

C3 = {
    "dataset_splitter" : split_dataset_random_plus_politics,
    "lookup_phi" : response_index_phi,
    "data_reader" : full_reader,
    "balanced_setting" : True,
    "author_phi_creator" : author_comment_counts_phi_creator,
    "author_feature_shape_placeholder" : (2,),
    "max_len" : 60,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 10,
    "dropout" : 0.1,
    "l2_lambda" : 1e-4,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : False,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 5,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

C4 = {
    "dataset_splitter" : split_dataset_random_plus_politics,
    "lookup_phi" : response_index_phi,
    "data_reader" : full_reader,
    "balanced_setting" : True,
    "author_phi_creator" : author_index_phi_creator,
    "author_feature_shape_placeholder" : (None, 15),
    "max_len" : 100,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 160,
    "dropout" : 0.3,
    "l2_lambda" : .001,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : True,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 5,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

D2 = {
    "dataset_splitter" : split_dataset_random_01,
    "lookup_phi" : response_index_phi,
    "data_reader" : pol_reader_unbalanced,
    "balanced_setting" : False,
    "recall_multiplier" : 4.,
    "max_len" : 60,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 10,
    "dropout" : 0.1,
    "l2_lambda" : 1e-4,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : False,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 5,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

D3 = {
    "dataset_splitter" : split_dataset_random_01,
    "lookup_phi" : response_index_phi,
    "data_reader" : pol_reader_unbalanced,
    "balanced_setting" : False,
    "recall_multiplier" : 4.,
    "author_phi_creator" : author_comment_counts_phi_creator,
    "author_feature_shape_placeholder" : (2,),
    "max_len" : 60,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 10,
    "dropout" : 0.1,
    "l2_lambda" : 1e-4,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : False,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 5,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

D4 = {
    "dataset_splitter" : split_dataset_random_01,
    "lookup_phi" : response_index_phi,
    "data_reader" : pol_reader_unbalanced,
    "balanced_setting" : False,
    "recall_multiplier" : 4.,
    "author_phi_creator" : author_index_phi_creator,
    "author_feature_shape_placeholder" : (None, 15),
    "max_len" : 100,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 160,
    "dropout" : 0.3,
    "l2_lambda" : .001,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : True,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 5,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

test_configs = {
    'B2' : B2,
    'B3' : B3,
    'B4' : B4,
    'C2' : C2,
    'C3' : C3,
    'C4' : C4,
    'D2' : D2,
    'D3' : D3,
    'D4' : D4
}


full_balanced_defaults = {
    "dataset_splitter" : split_dataset_random_plus_politics,
    "data_reader" : full_reader,
    "balanced_setting" : True,
    "subreddit_phi_creator" : subreddit_index_phi_creator,
    "subreddit_embed_dim" : 10,
    "max_len" : 60,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 10,
    "dropout" : 0.1,
    "l2_lambda" : 1e-4,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : False,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 3,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

pol_unbalanced_defaults = {
    "dataset_splitter" : split_dataset_random_05,
    "data_reader" : pol_reader_unbalanced,
    "balanced_setting" : False,
    "recall_multiplier" : 4.,
    "max_len" : 60,
    "Module" : SarcasmRNN,
    "attention_size" : None,
    "rnn_cell" : 'GRU',
    "hidden_dim" : 10,
    "dropout" : 0.1,
    "l2_lambda" : 1e-4,
    "lr" : 1e-3,
    "freeze_embeddings" : True,
    "num_rnn_layers" : 1,
    "second_linear_layer" : False,
    "batch_size" : 256,
    "max_epochs" : 100,
    "epochs_to_persist" : 3,
    "early_stopping" : True,
    "verbose" : False,
    "progress_bar" : True,
    "output_graphs" : False
}

